---
version: '2'
services:
    web:
        image: nginx
        ports:
            - 8080:80
        volumes:
             - ./nginx/sites-available:/etc/nginx/conf.d:ro
             - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
             - ./client:/home/ubuntu/uspto_ptab/searchtool/client:ro
             - ./bower_components:/home/ubuntu/uspto_ptab/searchtool/bower_components:ro
        depends_on:
             - appserver
    appserver:
         image: node
         command: node server/server.js
         ports:
             - 3000:3000
         volumes:
             - ./package.json:/package.json:ro
             - ./server:/server:ro
             - ./common:/common:ro
             - node_modules:/node_modules
             - ./bin:/node_scripts:ro
         environment:
             - NODE_PATH=/usr/lib/node_modules:/node_modules
         restart: always
         depends_on:
             - db
    db:
        image: mysql:5.7
        environment:
           - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - svc_data:/data
        ports:
            - 3306:3306

volumes:
    svc_data:
    node_modules:
